package io.devbits.gocart.composeui.theme

import androidx.compose.ui.graphics.Color

val go_cart_eggshell = Color(0xFFF6F6F6)
val go_cart_avocado = Color(0xFF257A00)
val go_cart_avocado_dark = Color(0xFF004D00)
val go_cart_sinopia = Color(0xFFC24E2E)
val go_cart_sinopia_dark = Color(0xFF8b1D04)
val go_cart_independence = Color(0xFF3D405B)
val go_cart_orange_yellow = Color(0xFFF6BD3A)
val black = Color(0xFF000000)
val dark_grey = Color(0xFF333335)
val white = Color(0xFFFFFFFF)
val white_70 = Color(0xB3FFFFFF)

val google_red = Color(0xFFDB4437)
val facebook_blue = Color(0xFF0078FF)

val md_theme_light_primary = go_cart_avocado
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF9EF979)
val md_theme_light_onPrimaryContainer = Color(0xFF052100)
val md_theme_light_secondary = go_cart_sinopia
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBD1)
val md_theme_light_onSecondaryContainer = Color(0xFF3B0800)
val md_theme_light_tertiary = Color(0xFF4C57A9)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDFE0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF000B62)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF001B3D)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF001B3D)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D7)
val md_theme_light_onSurfaceVariant = Color(0xFF43483F)
val md_theme_light_outline = Color(0xFF73796E)
val md_theme_light_inverseOnSurface = Color(0xFFECF0FF)
val md_theme_light_inverseSurface = Color(0xFF003062)
val md_theme_light_inversePrimary = Color(0xFF83DC60)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF206D00)
val md_theme_light_outlineVariant = Color(0xFFC3C8BB)
val md_theme_light_scrim = Color(0xFF000000)