package io.devbits.gocart.composeui.theme

import androidx.compose.ui.graphics.Color

val go_cart_eggshell = Color(0xFFF6F6F6)
val go_cart_avocado = Color(0xFF257A00)
val go_cart_avocado_dark = Color(0xFF004D00)
val go_cart_sinopia = Color(0xFFC24E2E)
val go_cart_sinopia_dark = Color(0xFF8b1D04)
val go_cart_independence = Color(0xFF3D405B)
val go_cart_orange_yellow = Color(0xFFF6BD3A)
val black = Color(0xFF000000)
val dark_grey = Color(0xFF333335)
val white = Color(0xFFFFFFFF)
val white_70 = Color(0xB3FFFFFF)

val google_red = Color(0xFFDB4437)
val facebook_blue = Color(0xFF0078FF)

val md_theme_light_primary = Color(0xFF206D00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF9EF979)
val md_theme_light_onPrimaryContainer = Color(0xFF052100)
val md_theme_light_secondary = Color(0xFFA63A1C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBD1)
val md_theme_light_onSecondaryContainer = Color(0xFF3B0800)
val md_theme_light_tertiary = Color(0xFF4C57A9)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDFE0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF000B62)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF001B3D)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF001B3D)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D7)
val md_theme_light_onSurfaceVariant = Color(0xFF43483F)
val md_theme_light_outline = Color(0xFF73796E)
val md_theme_light_inverseOnSurface = Color(0xFFECF0FF)
val md_theme_light_inverseSurface = Color(0xFF003062)
val md_theme_light_inversePrimary = Color(0xFF83DC60)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF206D00)
val md_theme_light_outlineVariant = Color(0xFFC3C8BB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF83DC60)
val md_theme_dark_onPrimary = Color(0xFF0D3900)
val md_theme_dark_primaryContainer = Color(0xFF165200)
val md_theme_dark_onPrimaryContainer = Color(0xFF9EF979)
val md_theme_dark_secondary = Color(0xFFFFB5A1)
val md_theme_dark_onSecondary = Color(0xFF601400)
val md_theme_dark_secondaryContainer = Color(0xFF862305)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBD1)
val md_theme_dark_tertiary = Color(0xFFBCC2FF)
val md_theme_dark_onTertiary = Color(0xFF1B2678)
val md_theme_dark_tertiaryContainer = Color(0xFF343F90)
val md_theme_dark_onTertiaryContainer = Color(0xFFDFE0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001B3D)
val md_theme_dark_onBackground = Color(0xFFD6E3FF)
val md_theme_dark_surface = Color(0xFF001B3D)
val md_theme_dark_onSurface = Color(0xFFD6E3FF)
val md_theme_dark_surfaceVariant = Color(0xFF43483F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BB)
val md_theme_dark_outline = Color(0xFF8D9387)
val md_theme_dark_inverseOnSurface = Color(0xFF001B3D)
val md_theme_dark_inverseSurface = Color(0xFFD6E3FF)
val md_theme_dark_inversePrimary = Color(0xFF206D00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF83DC60)
val md_theme_dark_outlineVariant = Color(0xFF43483F)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF257A00)
