name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [ "bug" ]
assignees: [ "etonotieno" ]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce the bug
      description: Steps to reproduce the behaviour
      placeholder: |
        1. With this config...
        2. Run '...'
        3. Click on '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.
  - type: textarea
    id: logs
    attributes:
      label: Relevant logcat output
      description: Please copy and paste any relevant logcat output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        # Environment
  - type: input
    id: android-version
    attributes:
      label: Android OS version
  - type: input
    id: device-type
    attributes:
      label: Device
  - type: input
    id: app-version
    attributes:
      label: App version
